import { buildApiPath, getBackendUrl } from 'src/services/backend';

export const API_BASE_URL = getBackendUrl();

export const END_POINT = {
  lieux: buildApiPath('/lieux'),
  lieuById: (id) => buildApiPath(`/lieux/${id}`),
  uploadLieuImages: buildApiPath('/lieux/upload-images'),
  users: buildApiPath('/users'),
  userById: (id) => buildApiPath(`/users/${id}`),
  updateUserStatus: (id) => buildApiPath(`/users/${id}/status`),
  toggleUserRole: (id) => buildApiPath(`/users/${id}/status`),
  banUser: (id) => buildApiPath(`/users/${id}/ban`),
  unbanUser: (id) => buildApiPath(`/users/${id}/unban`),
  posts: buildApiPath('/posts/admin'),
  postById: (id) => buildApiPath(`/posts/admin/${id}`),
  activites: buildApiPath('/activites/admin'),
  activiteById: (id) => buildApiPath(`/activites/admin/${id}`),
  paymentsAdmin: buildApiPath('/payments/all'),
  paymentById: (id) => buildApiPath(`/payments/${id}`),
  messageConversations: buildApiPath('/messages/conversations'),
  messageWith: (partnerId) => buildApiPath(`/messages/with/${partnerId}`),
  messageById: (messageId) => buildApiPath(`/messages/${messageId}`),
  systemLogs: buildApiPath('/system-logs'),
  activityLogs: buildApiPath('/logs'),
  adminComments: buildApiPath('/comments/admin'),
  adminCommentById: (id) => buildApiPath(`/comments/admin/${id}`),
  inscriptions: buildApiPath('/inscriptions'),
  inscriptionsByActivity: (activityId) => buildApiPath(`/inscriptions/admin/activity-participants?activite_id=${activityId}`),
  userReviews: (userId) => buildApiPath(`/avis/touriste/${userId}`),
  userPosts: (userId) => buildApiPath(`/posts/user/${userId}`),
  deleteReview: (reviewId) => buildApiPath(`/avis/admin/${reviewId}`),
  postComments: (postId) => buildApiPath(`/comments/${postId}/comments`),
  deleteComment: (commentId) => buildApiPath(`/comments/admin/${commentId}`),
};
