class Countries {
  static const List<Map<String, String>> all = [
    {'name': 'Afghanistan', 'code': 'AF', 'flag': '🇦🇫'},
    {'name': 'Afrique du Sud', 'code': 'ZA', 'flag': '🇿🇦'},
    {'name': 'Albanie', 'code': 'AL', 'flag': '🇦🇱'},
    {'name': 'Algérie', 'code': 'DZ', 'flag': '🇩🇿'},
    {'name': 'Allemagne', 'code': 'DE', 'flag': '🇩🇪'},
    {'name': 'Andorre', 'code': 'AD', 'flag': '🇦🇩'},
    {'name': 'Angola', 'code': 'AO', 'flag': '🇦🇴'},
    {'name': 'Arabie Saoudite', 'code': 'SA', 'flag': '🇸🇦'},
    {'name': 'Argentine', 'code': 'AR', 'flag': '🇦🇷'},
    {'name': 'Arménie', 'code': 'AM', 'flag': '🇦🇲'},
    {'name': 'Australie', 'code': 'AU', 'flag': '🇦🇺'},
    {'name': 'Autriche', 'code': 'AT', 'flag': '🇦🇹'},
    {'name': 'Azerbaïdjan', 'code': 'AZ', 'flag': '🇦🇿'},
    {'name': 'Bahamas', 'code': 'BS', 'flag': '🇧🇸'},
    {'name': 'Bahreïn', 'code': 'BH', 'flag': '🇧🇭'},
    {'name': 'Bangladesh', 'code': 'BD', 'flag': '🇧🇩'},
    {'name': 'Barbade', 'code': 'BB', 'flag': '🇧🇧'},
    {'name': 'Belgique', 'code': 'BE', 'flag': '🇧🇪'},
    {'name': 'Belize', 'code': 'BZ', 'flag': '🇧🇿'},
    {'name': 'Bénin', 'code': 'BJ', 'flag': '🇧🇯'},
    {'name': 'Bhoutan', 'code': 'BT', 'flag': '🇧🇹'},
    {'name': 'Biélorussie', 'code': 'BY', 'flag': '🇧🇾'},
    {'name': 'Bolivie', 'code': 'BO', 'flag': '🇧🇴'},
    {'name': 'Bosnie-Herzégovine', 'code': 'BA', 'flag': '🇧🇦'},
    {'name': 'Botswana', 'code': 'BW', 'flag': '🇧🇼'},
    {'name': 'Brésil', 'code': 'BR', 'flag': '🇧🇷'},
    {'name': 'Brunei', 'code': 'BN', 'flag': '🇧🇳'},
    {'name': 'Bulgarie', 'code': 'BG', 'flag': '🇧🇬'},
    {'name': 'Burkina Faso', 'code': 'BF', 'flag': '🇧🇫'},
    {'name': 'Burundi', 'code': 'BI', 'flag': '🇧🇮'},
    {'name': 'Cambodge', 'code': 'KH', 'flag': '🇰🇭'},
    {'name': 'Cameroun', 'code': 'CM', 'flag': '🇨🇲'},
    {'name': 'Canada', 'code': 'CA', 'flag': '🇨🇦'},
    {'name': 'Cap-Vert', 'code': 'CV', 'flag': '🇨🇻'},
    {'name': 'Chili', 'code': 'CL', 'flag': '🇨🇱'},
    {'name': 'Chine', 'code': 'CN', 'flag': '🇨🇳'},
    {'name': 'Chypre', 'code': 'CY', 'flag': '🇨🇾'},
    {'name': 'Colombie', 'code': 'CO', 'flag': '🇨🇴'},
    {'name': 'Comores', 'code': 'KM', 'flag': '🇰🇲'},
    {'name': 'Congo', 'code': 'CG', 'flag': '🇨🇬'},
    {'name': 'Corée du Nord', 'code': 'KP', 'flag': '🇰🇵'},
    {'name': 'Corée du Sud', 'code': 'KR', 'flag': '🇰🇷'},
    {'name': 'Costa Rica', 'code': 'CR', 'flag': '🇨🇷'},
    {'name': 'Côte d\'Ivoire', 'code': 'CI', 'flag': '🇨🇮'},
    {'name': 'Croatie', 'code': 'HR', 'flag': '🇭🇷'},
    {'name': 'Cuba', 'code': 'CU', 'flag': '🇨🇺'},
    {'name': 'Danemark', 'code': 'DK', 'flag': '🇩🇰'},
    {'name': 'Djibouti', 'code': 'DJ', 'flag': '🇩🇯'},
    {'name': 'Dominique', 'code': 'DM', 'flag': '🇩🇲'},
    {'name': 'Égypte', 'code': 'EG', 'flag': '🇪🇬'},
    {'name': 'Émirats arabes unis', 'code': 'AE', 'flag': '🇦🇪'},
    {'name': 'Équateur', 'code': 'EC', 'flag': '🇪🇨'},
    {'name': 'Érythrée', 'code': 'ER', 'flag': '🇪🇷'},
    {'name': 'Espagne', 'code': 'ES', 'flag': '🇪🇸'},
    {'name': 'Estonie', 'code': 'EE', 'flag': '🇪🇪'},
    {'name': 'États-Unis', 'code': 'US', 'flag': '🇺🇸'},
    {'name': 'Éthiopie', 'code': 'ET', 'flag': '🇪🇹'},
    {'name': 'Fidji', 'code': 'FJ', 'flag': '🇫🇯'},
    {'name': 'Finlande', 'code': 'FI', 'flag': '🇫🇮'},
    {'name': 'France', 'code': 'FR', 'flag': '🇫🇷'},
    {'name': 'Gabon', 'code': 'GA', 'flag': '🇬🇦'},
    {'name': 'Gambie', 'code': 'GM', 'flag': '🇬🇲'},
    {'name': 'Géorgie', 'code': 'GE', 'flag': '🇬🇪'},
    {'name': 'Ghana', 'code': 'GH', 'flag': '🇬🇭'},
    {'name': 'Grèce', 'code': 'GR', 'flag': '🇬🇷'},
    {'name': 'Grenade', 'code': 'GD', 'flag': '🇬🇩'},
    {'name': 'Guatemala', 'code': 'GT', 'flag': '🇬🇹'},
    {'name': 'Guinée', 'code': 'GN', 'flag': '🇬🇳'},
    {'name': 'Guinée équatoriale', 'code': 'GQ', 'flag': '🇬🇶'},
    {'name': 'Guinée-Bissau', 'code': 'GW', 'flag': '🇬🇼'},
    {'name': 'Guyana', 'code': 'GY', 'flag': '🇬🇾'},
    {'name': 'Haïti', 'code': 'HT', 'flag': '🇭🇹'},
    {'name': 'Honduras', 'code': 'HN', 'flag': '🇭🇳'},
    {'name': 'Hongrie', 'code': 'HU', 'flag': '🇭🇺'},
    {'name': 'Inde', 'code': 'IN', 'flag': '🇮🇳'},
    {'name': 'Indonésie', 'code': 'ID', 'flag': '🇮🇩'},
    {'name': 'Irak', 'code': 'IQ', 'flag': '🇮🇶'},
    {'name': 'Iran', 'code': 'IR', 'flag': '🇮🇷'},
    {'name': 'Irlande', 'code': 'IE', 'flag': '🇮🇪'},
    {'name': 'Islande', 'code': 'IS', 'flag': '🇮🇸'},
    {'name': 'Israël', 'code': 'IL', 'flag': '🇮🇱'},
    {'name': 'Italie', 'code': 'IT', 'flag': '🇮🇹'},
    {'name': 'Jamaïque', 'code': 'JM', 'flag': '🇯🇲'},
    {'name': 'Japon', 'code': 'JP', 'flag': '🇯🇵'},
    {'name': 'Jordanie', 'code': 'JO', 'flag': '🇯🇴'},
    {'name': 'Kazakhstan', 'code': 'KZ', 'flag': '🇰🇿'},
    {'name': 'Kenya', 'code': 'KE', 'flag': '🇰🇪'},
    {'name': 'Kirghizistan', 'code': 'KG', 'flag': '🇰🇬'},
    {'name': 'Kiribati', 'code': 'KI', 'flag': '🇰🇮'},
    {'name': 'Kosovo', 'code': 'XK', 'flag': '🇽🇰'},
    {'name': 'Koweït', 'code': 'KW', 'flag': '🇰🇼'},
    {'name': 'Laos', 'code': 'LA', 'flag': '🇱🇦'},
    {'name': 'Lesotho', 'code': 'LS', 'flag': '🇱🇸'},
    {'name': 'Lettonie', 'code': 'LV', 'flag': '🇱🇻'},
    {'name': 'Liban', 'code': 'LB', 'flag': '🇱🇧'},
    {'name': 'Libéria', 'code': 'LR', 'flag': '🇱🇷'},
    {'name': 'Libye', 'code': 'LY', 'flag': '🇱🇾'},
    {'name': 'Liechtenstein', 'code': 'LI', 'flag': '🇱🇮'},
    {'name': 'Lituanie', 'code': 'LT', 'flag': '🇱🇹'},
    {'name': 'Luxembourg', 'code': 'LU', 'flag': '🇱🇺'},
    {'name': 'Macédoine du Nord', 'code': 'MK', 'flag': '🇲🇰'},
    {'name': 'Madagascar', 'code': 'MG', 'flag': '🇲🇬'},
    {'name': 'Malaisie', 'code': 'MY', 'flag': '🇲🇾'},
    {'name': 'Malawi', 'code': 'MW', 'flag': '🇲🇼'},
    {'name': 'Maldives', 'code': 'MV', 'flag': '🇲🇻'},
    {'name': 'Mali', 'code': 'ML', 'flag': '🇲🇱'},
    {'name': 'Malte', 'code': 'MT', 'flag': '🇲🇹'},
    {'name': 'Maroc', 'code': 'MA', 'flag': '🇲🇦'},
    {'name': 'Maurice', 'code': 'MU', 'flag': '🇲🇺'},
    {'name': 'Mauritanie', 'code': 'MR', 'flag': '🇲🇷'},
    {'name': 'Mexique', 'code': 'MX', 'flag': '🇲🇽'},
    {'name': 'Moldavie', 'code': 'MD', 'flag': '🇲🇩'},
    {'name': 'Monaco', 'code': 'MC', 'flag': '🇲🇨'},
    {'name': 'Mongolie', 'code': 'MN', 'flag': '🇲🇳'},
    {'name': 'Monténégro', 'code': 'ME', 'flag': '🇲🇪'},
    {'name': 'Mozambique', 'code': 'MZ', 'flag': '🇲🇿'},
    {'name': 'Myanmar', 'code': 'MM', 'flag': '🇲🇲'},
    {'name': 'Namibie', 'code': 'NA', 'flag': '🇳🇦'},
    {'name': 'Nauru', 'code': 'NR', 'flag': '🇳🇷'},
    {'name': 'Népal', 'code': 'NP', 'flag': '🇳🇵'},
    {'name': 'Nicaragua', 'code': 'NI', 'flag': '🇳🇮'},
    {'name': 'Niger', 'code': 'NE', 'flag': '🇳🇪'},
    {'name': 'Nigéria', 'code': 'NG', 'flag': '🇳🇬'},
    {'name': 'Norvège', 'code': 'NO', 'flag': '🇳🇴'},
    {'name': 'Nouvelle-Zélande', 'code': 'NZ', 'flag': '🇳🇿'},
    {'name': 'Oman', 'code': 'OM', 'flag': '🇴🇲'},
    {'name': 'Ouganda', 'code': 'UG', 'flag': '🇺🇬'},
    {'name': 'Ouzbékistan', 'code': 'UZ', 'flag': '🇺🇿'},
    {'name': 'Pakistan', 'code': 'PK', 'flag': '🇵🇰'},
    {'name': 'Palaos', 'code': 'PW', 'flag': '🇵🇼'},
    {'name': 'Palestine', 'code': 'PS', 'flag': '🇵🇸'},
    {'name': 'Panama', 'code': 'PA', 'flag': '🇵🇦'},
    {'name': 'Papouasie-Nouvelle-Guinée', 'code': 'PG', 'flag': '🇵🇬'},
    {'name': 'Paraguay', 'code': 'PY', 'flag': '🇵🇾'},
    {'name': 'Pays-Bas', 'code': 'NL', 'flag': '🇳🇱'},
    {'name': 'Pérou', 'code': 'PE', 'flag': '🇵🇪'},
    {'name': 'Philippines', 'code': 'PH', 'flag': '🇵🇭'},
    {'name': 'Pologne', 'code': 'PL', 'flag': '🇵🇱'},
    {'name': 'Portugal', 'code': 'PT', 'flag': '🇵🇹'},
    {'name': 'Qatar', 'code': 'QA', 'flag': '🇶🇦'},
    {'name': 'République centrafricaine', 'code': 'CF', 'flag': '🇨🇫'},
    {'name': 'République dominicaine', 'code': 'DO', 'flag': '🇩🇴'},
    {'name': 'République tchèque', 'code': 'CZ', 'flag': '🇨🇿'},
    {'name': 'Roumanie', 'code': 'RO', 'flag': '🇷🇴'},
    {'name': 'Royaume-Uni', 'code': 'GB', 'flag': '🇬🇧'},
    {'name': 'Russie', 'code': 'RU', 'flag': '🇷🇺'},
    {'name': 'Rwanda', 'code': 'RW', 'flag': '🇷🇼'},
    {'name': 'Saint-Marin', 'code': 'SM', 'flag': '🇸🇲'},
    {'name': 'Sainte-Lucie', 'code': 'LC', 'flag': '🇱🇨'},
    {'name': 'Salvador', 'code': 'SV', 'flag': '🇸🇻'},
    {'name': 'Samoa', 'code': 'WS', 'flag': '🇼🇸'},
    {'name': 'Sénégal', 'code': 'SN', 'flag': '🇸🇳'},
    {'name': 'Serbie', 'code': 'RS', 'flag': '🇷🇸'},
    {'name': 'Seychelles', 'code': 'SC', 'flag': '🇸🇨'},
    {'name': 'Sierra Leone', 'code': 'SL', 'flag': '🇸🇱'},
    {'name': 'Singapour', 'code': 'SG', 'flag': '🇸🇬'},
    {'name': 'Slovaquie', 'code': 'SK', 'flag': '🇸🇰'},
    {'name': 'Slovénie', 'code': 'SI', 'flag': '🇸🇮'},
    {'name': 'Somalie', 'code': 'SO', 'flag': '🇸🇴'},
    {'name': 'Soudan', 'code': 'SD', 'flag': '🇸🇩'},
    {'name': 'Soudan du Sud', 'code': 'SS', 'flag': '🇸🇸'},
    {'name': 'Sri Lanka', 'code': 'LK', 'flag': '🇱🇰'},
    {'name': 'Suède', 'code': 'SE', 'flag': '🇸🇪'},
    {'name': 'Suisse', 'code': 'CH', 'flag': '🇨🇭'},
    {'name': 'Suriname', 'code': 'SR', 'flag': '🇸🇷'},
    {'name': 'Syrie', 'code': 'SY', 'flag': '🇸🇾'},
    {'name': 'Tadjikistan', 'code': 'TJ', 'flag': '🇹🇯'},
    {'name': 'Tanzanie', 'code': 'TZ', 'flag': '🇹🇿'},
    {'name': 'Tchad', 'code': 'TD', 'flag': '🇹🇩'},
    {'name': 'Thaïlande', 'code': 'TH', 'flag': '🇹🇭'},
    {'name': 'Timor oriental', 'code': 'TL', 'flag': '🇹🇱'},
    {'name': 'Togo', 'code': 'TG', 'flag': '🇹🇬'},
    {'name': 'Tonga', 'code': 'TO', 'flag': '🇹🇴'},
    {'name': 'Trinité-et-Tobago', 'code': 'TT', 'flag': '🇹🇹'},
    {'name': 'Tunisie', 'code': 'TN', 'flag': '🇹🇳'},
    {'name': 'Turkménistan', 'code': 'TM', 'flag': '🇹🇲'},
    {'name': 'Turquie', 'code': 'TR', 'flag': '🇹🇷'},
    {'name': 'Tuvalu', 'code': 'TV', 'flag': '🇹🇻'},
    {'name': 'Ukraine', 'code': 'UA', 'flag': '🇺🇦'},
    {'name': 'Uruguay', 'code': 'UY', 'flag': '🇺🇾'},
    {'name': 'Vanuatu', 'code': 'VU', 'flag': '🇻🇺'},
    {'name': 'Vatican', 'code': 'VA', 'flag': '🇻🇦'},
    {'name': 'Venezuela', 'code': 'VE', 'flag': '🇻🇪'},
    {'name': 'Viêt Nam', 'code': 'VN', 'flag': '🇻🇳'},
    {'name': 'Yémen', 'code': 'YE', 'flag': '🇾🇪'},
    {'name': 'Zambie', 'code': 'ZM', 'flag': '🇿🇲'},
    {'name': 'Zimbabwe', 'code': 'ZW', 'flag': '🇿🇼'},
  ];

  static List<Map<String, String>> search(String query) {
    if (query.isEmpty) return all;
    final lowerQuery = query.toLowerCase();
    return all
        .where(
          (country) =>
              country['name']!.toLowerCase().contains(lowerQuery) ||
              country['code']!.toLowerCase().contains(lowerQuery),
        )
        .toList();
  }
}
